# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # Nommer la machine
    config.vm.define "ubuntu22" do |node|
      # Configuration de la box Ubuntu 22.04
      node.vm.box = "generic/ubuntu2204"
  
      # Configuration du fournisseur Hyper-V
      node.vm.provider "hyperv" do |hv|
        # Specify the Hyper-V network name
        hv.network_name = "Default Switch"
  
        # Enable automatic restart after the host machine reboots
        hv.restart_mode = "always"
      end
  
      # Configuration du réseau NAT
      node.vm.network "forwarded_port", guest: 22, host: 2222, auto_correct: true
      node.vm.network "forwarded_port", guest: 80, host: 8181
  
      # Configuration du réseau Bridge (public)
      node.vm.network "public_network"
  
      # Configuration du réseau privé
      node.vm.network "private_network", type: "dhcp"
  
      # Configuration de l'exécution des playbooks Ansible
      node.vm.provision "ansible" do |ansible|
        ansible.playbook = "install-docker.yml"
      end
  
      # Ajout du playbook configure-docker.yml
      node.vm.provision "ansible" do |ansible|
        ansible.playbook = "configure-docker.yml"
      end
    end
  end
  
  
  