global:
  resolve_timeout: 1m
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  receiver: 'lab-alert-manager'
  repeat_interval: 1m
receivers:
- name: 'lab-alert-manager'
  slack_configs:
  - send_resolved: true
    channel: '#your channel name'
    api_url: 'webhook url'
email_configs:
  - to: 'lab.inbox@gmail.com'
    from: 'lab.outbox@gmail.com'
    smarthost: 'smtp.gmail.com:587'
    auth_username: 'lab.outbox@gmail.com'
    auth_identity: 'lab.outbox@gmail.com'
    auth_password: 'AppPassword'
    send_resolved: true


